### PR TITLE
Added years to clock, still sad

### PR DESCRIPTION
**Pull request by vingkan**
In response to issue #42

### CODE REVIEW

**Comment by cathydeng** [comment]
thx @vingkan! just wana add that with the additional year chunk added, we should make sure that the clock still looks ok on phones, i.e. text doesn't wrap at width 320px

**Comment by cathydeng** [comment]
relevant css here: https://github.com/chihacknight/il-budget-clock/blob/master/css/custom.css#L223-L229

**Comment by connorsb** [comment]
Yinz know about Brad Frost's ISH tool? Great little hack for making sure
things look good on any viewscreen.
http://bradfrost.com/demo/ish/?url=http%3A%2F%2Filbudgetclock.com#s

On Mon, Jun 27, 2016 at 4:05 PM Cathy Deng notifications@github.com wrote:

> thx @vingkan https://github.com/vingkan! just wana add that with the
> additional year chunk added, we should make sure that the clock still looks
> ok on phones, i.e. text doesn't wrap at width 320px
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> https://github.com/chihacknight/il-budget-clock/pull/43#issuecomment-228859214,
> or mute the thread
> https://github.com/notifications/unsubscribe/AGFabUXqHqKZ-jNklL09gqW4fKGuLye7ks5qQC0agaJpZM4I_buP
> .
> 
> ## 

Sent from a small screen.

**Comment by cathydeng** [comment]
@connorsb looks like ish is for deployed sites, rather than for local development? I don't know of any ways around using the browser page inspector for testing window sizes while developing locally.

@vingkan do you want to fix the css or should I?

**Comment by vingkan** [comment]
@cathydeng How does this look for desktop vs mobile?

Desktop Style
Mobile Style

**Comment by derekeder** [comment]
Whelp, a temporary stopgap budget was passed today: http://chicago.suntimes.com/news/budget-bills-pass-illinois-house-amid-last-minute-drama/

Going off of the assessment of Chris Kaergard and his #budgetbeard, we will be stopping the clock and posting a message accordingly.

So thankfully, a adding a years position will not be needed.

**Pull request closed without merging**
